name: my_cv
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter
  
  font_awesome_flutter: ^10.12.0
  url_launcher: ^6.3.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Pema.jpg
  fonts:
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans_Condensed-regular.ttf
      